In [3]:
import numpy as np

# create 1d tensor

In [17]:
arr=np.array([0,2,3,5,7,8,9])

In [19]:
arr

array([0, 2, 3, 5, 7, 8, 9])

In [21]:
arr.ndim

1

# create 2d tensor

In [29]:
arr2=np.array([[0,1],[2,3],[23,34]])

In [31]:
arr2

array([[ 0,  1],
       [ 2,  3],
       [23, 34]])

In [33]:
arr2.ndim

2

In [35]:
arr2.size

6

In [37]:
arr2.shape

(3, 2)

# 3d tensor

In [39]:
tensor=np.array([
    [  # Shelf 1
        [1, 2, 3, 4],  # Book 1
        [5, 6, 7, 8],  # Book 2
        [9, 10,11, 12]  # Book 3
    ],
    [  # Shelf 2
        [13, 14, 15, 16],  # Book 4
        [17, 18, 19, 20],  # Book 5
        [21, 22, 23, 24]  # Book 6
    ]
]
)

In [41]:
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [43]:
tensor.ndim

3

In [45]:
tensor.shape

(2, 3, 4)

In [47]:
tensor.size

24

In [63]:
tensor1=np.array([

               [
                 [1,2,3,4],
                 [2,3,4,5],
                 [4,3,5,6]  
                   
               ],
               
               [
                 [1,0,3,0],
                 [2,87,4,5],
                 [4,2,5,6] 
               ]
    
]
                )
                 
    
   

In [65]:
tensor1

array([[[ 1,  2,  3,  4],
        [ 2,  3,  4,  5],
        [ 4,  3,  5,  6]],

       [[ 1,  0,  3,  0],
        [ 2, 87,  4,  5],
        [ 4,  2,  5,  6]]])

In [67]:
tensor1.shape

(2, 3, 4)